apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-scheduler-ingress
  namespace: smart-scheduler
spec:
  ingressClassName: traefik              # k3s auto with Traefik
  rules:
    - host: smart-scheduler.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80